export const YTVideos = [
  "https://www.youtube.com/watch/u1kDmE2Ou3I",
  "https://www.youtube.com/watch/PfqsHIITt8c",
  "https://www.youtube.com/watch/KxVqCoKfujU",
  "https://www.youtube.com/watch/yCWpOTJIXzM",
  "https://www.youtube.com/watch/ToFWx29MZzs",
  "https://www.youtube.com/watch/K9CWddpjq1E",
  "https://www.youtube.com/watch/ZUTLz8hPYJs",
  "https://www.youtube.com/watch/BiVdV2tFOZw",
  "https://www.youtube.com/watch/heF1N3B9SPM",
  "https://www.youtube.com/watch/ksWY6Kfa7qE",
  "https://www.youtube.com/watch/ChuwrrY0gtk",
  "https://www.youtube.com/watch/GfAKAqbyVXc",
  "https://www.youtube.com/watch/RCmoQ80J6m4",
  "https://www.youtube.com/watch/b3qisotgfmc",
  "https://www.youtube.com/embed/LRoq10n8DOo",
];

export const YTModalVideos = [
  "https://www.youtube.com/embed/u1kDmE2Ou3I",
  "https://www.youtube.com/embed/PfqsHIITt8c",
  "https://www.youtube.com/embed/KxVqCoKfujU",
  "https://www.youtube.com/embed/yCWpOTJIXzM",
  "https://www.youtube.com/embed/ToFWx29MZzs",
  "https://www.youtube.com/embed/K9CWddpjq1E",
  "https://www.youtube.com/embed/ZUTLz8hPYJs",
  "https://www.youtube.com/embed/BiVdV2tFOZw",
  "https://www.youtube.com/embed/heF1N3B9SPM",
  "https://www.youtube.com/embed/ksWY6Kfa7qE",
  "https://www.youtube.com/embed/ChuwrrY0gtk",
  "https://www.youtube.com/embed/GfAKAqbyVXc",
  "https://www.youtube.com/embed/RCmoQ80J6m4",
  "https://www.youtube.com/embed/b3qisotgfmc",
  "https://www.youtube.com/embed/LRoq10n8DOo",
];

export const YTThumbnail = [
  "https://img.youtube.com/vi/u1kDmE2Ou3I/0.jpg",
  "https://img.youtube.com/vi/PfqsHIITt8c/0.jpg",
  "https://img.youtube.com/vi/KxVqCoKfujU/0.jpg",
  "https://img.youtube.com/vi/yCWpOTJIXzM/0.jpg",
  "https://img.youtube.com/vi/ToFWx29MZzs/0.jpg",
  "https://img.youtube.com/vi/K9CWddpjq1E/0.jpg",
  "https://img.youtube.com/vi/ZUTLz8hPYJs/0.jpg",
  "https://img.youtube.com/vi/BiVdV2tFOZw/0.jpg",
  "https://img.youtube.com/vi/heF1N3B9SPM/0.jpg",
  "https://img.youtube.com/vi/ksWY6Kfa7qE/0.jpg",
  "https://img.youtube.com/vi/ChuwrrY0gtk/0.jpg",
  "https://img.youtube.com/vi/GfAKAqbyVXc/0.jpg",
  "https://img.youtube.com/vi/RCmoQ80J6m4/0.jpg",
  "https://img.youtube.com/vi/b3qisotgfmc/0.jpg",
  "https://img.youtube.com/vi/LRoq10n8DOo/0.jpg",
];
